services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  app:
    image: ghcr.io/michaelsaville/dochub:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db

  db:
    ports:
      - "5432:5432"
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/michael/.docker/config.json:/config.json
    command: --interval 30 --cleanup

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
